#
#
#

# Once the MONO path variables are set, this target will generate the project
# euler problem 1 solution in C#.
# Enter in: make mono_project and it will compile.
mono_project : multiples_3_5_mono.cs
	gmcs multiples_3_5_mono.cs

# This will generate the C++ example of the ProjectEuler problem 1.
cpp_project : multiples_of_3_5.cpp
	g++ multiples_of_3_5.cpp -o multiples_of_3_5.exe

# This will compile the Java version of hte Project Euler problem 1
java_project : Multiples_of_3_5.java
	javac Multiples_of_3_5.java